name: ogni_tipo_di_insegnamento
description: Ogni tipo di insegnamento - app cristiana


publish_to: 'none'

version: 26.3.5+24

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.4
  path_provider: ^2.1.5
  flutter_cache_manager: ^3.3.1
  open_filex: ^4.7.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  msix: ^3.16.7

flutter_launcher_icons:
  android: true
  ios: true
  macos: true
  image_path: "assets/icona.png"
  adaptive_icon_background: "#F5E66B"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"

msix_config:
  display_name: Ogni tipo di insegnamento
  publisher_display_name: Ogni tipo di insegnamento
  identity_name: Ognitipodiinsegnamento.Ognitipodiinsegnamento
  publisher: CN=A14F0C55-60F5-46B6-A3F1-5759F59A12FC
  msix_version: 26.3.5.0
  logo_path: assets\icona.ico
  store: true

flutter:
  uses-material-design: true

  assets:
    - assets/